import { createContext, useContext, useEffect, useState } from 'react';
import { Link, NavLink, Outlet, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { api } from './api';
import './App.css';

const AuthContext = createContext(null);

function useAuth() { return useContext(AuthContext); }

function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(Boolean(localStorage.getItem('pharmacy_token')));
  useEffect(() => {
    if (!localStorage.getItem('pharmacy_token')) return;
    api.me().then((data) => setUser(data.user)).catch(() => localStorage.removeItem('pharmacy_token')).finally(() => setLoading(false));
  }, []);
  const signIn = (data) => { localStorage.setItem('pharmacy_token', data.token); setUser(data.user); };
  const signOut = () => { localStorage.removeItem('pharmacy_token'); setUser(null); };
  return <AuthContext.Provider value={{ user, loading, signIn, signOut }}>{children}</AuthContext.Provider>;
}

function ProtectedRoute() {
  const { user, loading } = useAuth();
  if (loading) return <div className="center-message">Checking your session...</div>;
  if (!user) return <NavigateToLogin />;
  return <AppLayout />;
}
function NavigateToLogin() { const navigate = useNavigate(); useEffect(() => navigate('/login', { replace: true }), [navigate]); return <div className="center-message">Redirecting to login...</div>; }

function AppLayout() {
  const { user, signOut } = useAuth();
  return <div className="app-shell"><aside className="sidebar"><Link className="brand" to="/dashboard"><span className="brand-mark">+</span><span>InDate</span></Link><p className="sidebar-label">Workspace</p><nav className="nav-list"><NavLink to="/dashboard">Dashboard</NavLink><NavLink to="/medicines">Medicines</NavLink><NavLink to="/dispense">Dispense</NavLink><NavLink to="/alerts">Expiry alerts</NavLink><NavLink to="/history">History</NavLink></nav><div className="sidebar-footer"><div className="user-chip"><span className="avatar">{user.name[0]}</span><span><strong>{user.name}</strong><small>{user.role}</small></span></div><button className="button button-quiet" onClick={signOut}>Sign out</button></div></aside><main className="main-content"><Outlet /></main></div>;
}

function PageHeader({ eyebrow, title, description, action }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action}</header>; }
function Loading() { return <div className="panel muted">Loading...</div>; }
function ErrorMessage({ message }) { return message ? <div className="error-box">{message}</div> : null; }
function Empty({ children }) { return <div className="panel empty">{children}</div>; }
function Pagination({ pagination, onChange }) { if (!pagination || pagination.pages <= 1) return null; return <div className="pagination"><span>Page {pagination.page} of {pagination.pages}</span><div><button className="button button-small" disabled={pagination.page === 1} onClick={() => onChange(pagination.page - 1)}>Previous</button><button className="button button-small" disabled={pagination.page === pagination.pages} onClick={() => onChange(pagination.page + 1)}>Next</button></div></div>; }
function SortSelect({ value, onChange, children }) { return <label className="sort-control">Sort by <select value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>; }

function LandingPage() {
  return <div className="landing"><nav className="landing-nav"><Link className="brand dark-brand" to="/"><span className="brand-mark">+</span><span>InDate</span></Link><div><Link className="text-link" to="/login">Log in</Link><Link className="button button-primary" to="/register">Create account</Link></div></nav><section className="landing-hero"><div><p className="eyebrow">Pharmacy stock, kept in date</p><h1>Know what is sellable. Dispense what expires first.</h1><p className="hero-copy">InDate gives pharmacy teams a clear view of medicine batches, expiry risk, and FEFO dispensing in one quiet workspace.</p><div className="hero-actions"><Link className="button button-primary" to="/register">Get started</Link><a className="button button-outline" href="#features">See how it helps</a></div></div><div className="hero-board"><div className="board-top"><span>Stock health</span><span className="status-dot">Live</span></div><strong>94%</strong><p>in-date units</p><div className="mini-bars"><i /><i /><i /><i /><i /><i /><i /></div></div></section><section id="features" className="landing-section"><p className="eyebrow">Built for the counter</p><h2>A simpler rhythm for busy pharmacy teams.</h2><div className="feature-grid"><Feature number="01" title="Search in-date stock" text="Answer availability questions with a sellable quantity that excludes expired batches." /><Feature number="02" title="Dispense FEFO" text="The system selects the earliest-expiring valid batch and records every allocation." /><Feature number="03" title="Act on expiry risk" text="See approaching and expired batches before they become a surprise." /></div></section><section className="audience"><div><p className="eyebrow">For neighbourhood pharmacies</p><h2>Less guesswork between receiving and dispensing.</h2></div><p>InDate helps pharmacists and stock managers keep inventory accurate, auditable, and ready for the next patient.</p></section><section className="next-section"><p className="eyebrow">Next on the roadmap</p><h2>Three useful things to build next.</h2><div className="next-grid"><span>Low-stock reorder reminders</span><span>Supplier and purchase orders</span><span>Prescription and sales integrations</span></div></section><footer className="landing-footer">InDate pharmacy inventory</footer></div>;
}
function Feature({ number, title, text }) { return <article className="feature"><span>{number}</span><h3>{title}</h3><p>{text}</p></article>; }

function AuthPage({ mode }) {
  const { user, signIn } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const isRegister = mode === 'register';
  useEffect(() => { if (user) navigate('/dashboard', { replace: true }); }, [user, navigate]);
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { signIn(isRegister ? await api.register(form) : await api.login({ email: form.email, password: form.password })); navigate('/dashboard'); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  return <div className="auth-page"><Link className="brand dark-brand" to="/"><span className="brand-mark">+</span><span>InDate</span></Link><div className="auth-card"><p className="eyebrow">{isRegister ? 'New workspace' : 'Welcome back'}</p><h1>{isRegister ? 'Create your account' : 'Sign in to InDate'}</h1><p className="page-description">{isRegister ? 'Start tracking sellable stock in minutes.' : 'Your stock picture is waiting.'}</p><form onSubmit={submit}>{isRegister && <label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><ErrorMessage message={error} /><button className="button button-primary button-wide" disabled={busy}>{busy ? 'Working...' : isRegister ? 'Create account' : 'Log in'}</button></form><p className="auth-switch">{isRegister ? 'Already have an account?' : 'Need an account?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Register'}</Link></p></div></div>;
}

function DashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.medicines({ limit: 100 }), api.expiring({ limit: 5 }), api.expired({ limit: 5 }), api.dispensingHistory({ limit: 5 })]).then(([medicines, expiring, expired, history]) => setData({ medicines, expiring, expired, history })).catch((e) => setError(e.message)); }, []);
  if (!data) return <><PageHeader eyebrow="Overview" title="Dashboard" description="A quick read of stock health and the next actions." /><ErrorMessage message={error} />{!error && <Loading />}</>;
  const sellable = data.medicines.items.reduce((total, item) => total + item.stock.sellableQuantity, 0);
  return <><PageHeader eyebrow="Overview" title="Dashboard" description="A quick read of stock health and the next actions." action={<Link className="button button-primary" to="/dispense">Dispense medicine</Link>} /><section className="stat-grid"><Stat label="Sellable units" value={sellable} tone="green" /><Stat label="Medicines tracked" value={data.medicines.pagination.total} /><Stat label="Expiring soon" value={data.expiring.pagination.total} tone="amber" /><Stat label="Expired stock" value={data.expired.pagination.total} tone="red" /></section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Attention</p><h2>Expiring soon</h2></div><Link className="text-link" to="/alerts">View all</Link></div>{data.expiring.items.length ? <AlertTable items={data.expiring.items} /> : <Empty>No in-date batches are expiring in the next 30 days.</Empty>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Latest</p><h2>Recent dispensing</h2></div><Link className="text-link" to="/history">View history</Link></div>{data.history.items.length ? <HistoryTable items={data.history.items} compact /> : <Empty>No dispensing recorded yet.</Empty>}</section></div></>;
}
function Stat({ label, value, tone = '' }) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }

function MedicinesPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const search = searchParams.get('search') || ''; const page = Number(searchParams.get('page') || 1); const sortBy = searchParams.get('sortBy') || 'name';
  const [input, setInput] = useState(search); const [data, setData] = useState(null); const [error, setError] = useState(''); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState({ name: '', genericName: '', strength: '', form: '' });
  const load = () => api.medicines({ search, page, limit: 10, sortBy }).then(setData).catch((e) => setError(e.message));
  useEffect(load, [search, page, sortBy]);
  const submitSearch = (event) => { event.preventDefault(); setSearchParams({ ...(input ? { search: input } : {}) }); };
  const create = async (event) => { event.preventDefault(); try { await api.createMedicine(form); setForm({ name: '', genericName: '', strength: '', form: '' }); setShowCreate(false); load(); } catch (e) { setError(e.message); } };
  return <><PageHeader eyebrow="Inventory" title="Medicines" description="Search medicines and see their sellable stock at a glance." action={<button className="button button-primary" onClick={() => setShowCreate(!showCreate)}>+ Add medicine</button>} />{showCreate && <form className="panel inline-form" onSubmit={create}><h2>New medicine</h2><div className="form-grid"><Field label="Name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} required /><Field label="Generic name" value={form.genericName} onChange={(value) => setForm({ ...form, genericName: value })} /><Field label="Strength" value={form.strength} onChange={(value) => setForm({ ...form, strength: value })} /><Field label="Form" value={form.form} onChange={(value) => setForm({ ...form, form: value })} /></div><button className="button button-primary">Save medicine</button></form>}<section className="toolbar"><form className="search-form" onSubmit={submitSearch}><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Search by medicine name..." /><button className="button button-dark">Search</button></form><SortSelect value={sortBy} onChange={(value) => setSearchParams({ ...(search ? { search } : {}), sortBy: value })}><option value="name">Name</option><option value="createdAt">Recently added</option><option value="updatedAt">Recently updated</option></SortSelect></section><ErrorMessage message={error} />{!data && !error ? <Loading /> : data?.items.length ? <><div className="panel table-panel"><table><thead><tr><th>Medicine</th><th>Details</th><th>Sellable stock</th><th>Next expiry</th><th /></tr></thead><tbody>{data.items.map((medicine) => <tr key={medicine._id}><td><Link className="table-link" to={`/medicines/${medicine._id}`}>{medicine.name}</Link></td><td>{[medicine.strength, medicine.form].filter(Boolean).join(' · ') || '—'}</td><td><strong>{medicine.stock.sellableQuantity}</strong> units</td><td>{medicine.stock.nextExpiry ? formatDate(medicine.stock.nextExpiry.expiryDate) : '—'}</td><td><Link className="text-link" to={`/medicines/${medicine._id}`}>Open</Link></td></tr>)}</tbody></table></div><Pagination pagination={data.pagination} onChange={(nextPage) => setSearchParams({ ...(search ? { search } : {}), ...(sortBy ? { sortBy } : {}), page: nextPage })} /></> : <Empty>No medicines found.</Empty>}</>;
}

function MedicinePage() {
  const { medicineId } = useParams(); const navigate = useNavigate(); const [data, setData] = useState(null); const [batches, setBatches] = useState(null); const [batchPage, setBatchPage] = useState(1); const [batchSort, setBatchSort] = useState('expiryDate'); const [error, setError] = useState(''); const [showBatch, setShowBatch] = useState(false); const [batchForm, setBatchForm] = useState({ batchNumber: '', expiryDate: '', receivedDate: '', quantityReceived: '' });
  const load = () => Promise.all([api.medicine(medicineId), api.batches(medicineId, { page: batchPage, limit: 10, sortBy: batchSort })]).then(([medicine, batchData]) => { setData(medicine); setBatches(batchData); }).catch((e) => setError(e.message));
  useEffect(load, [medicineId, batchPage, batchSort]);
  if (!data || !batches) return <><PageHeader eyebrow="Inventory" title="Medicine details" /><ErrorMessage message={error} />{!error && <Loading />}</>;
  const addBatch = async (event) => { event.preventDefault(); try { await api.createBatch(medicineId, batchForm); setBatchForm({ batchNumber: '', expiryDate: '', receivedDate: '', quantityReceived: '' }); setShowBatch(false); setBatchPage(1); load(); } catch (e) { setError(e.message); } };
  const remove = async () => { if (!window.confirm('Delete this medicine?')) return; try { await api.deleteMedicine(medicineId); navigate('/medicines'); } catch (e) { setError(e.message); } };
  return <><PageHeader eyebrow="Medicine" title={data.medicine.name} description={[data.medicine.genericName, data.medicine.strength, data.medicine.form].filter(Boolean).join(' · ')} action={<div className="button-row"><Link className="button button-primary" to={`/dispense?medicineId=${medicineId}`}>Dispense</Link><button className="button button-outline" onClick={() => setShowBatch(!showBatch)}>+ Add batch</button><button className="button button-danger-text" onClick={remove}>Delete</button></div>} /><section className="stat-grid"><Stat label="Sellable units" value={data.stock.sellableQuantity} tone="green" /><Stat label="Expired units" value={data.stock.expiredQuantity} tone="red" /><Stat label="Batches" value={batches.pagination.total} /><Stat label="Next expiry" value={data.stock.nextExpiry ? formatDate(data.stock.nextExpiry.expiryDate) : '—'} tone="amber" /></section>{showBatch && <form className="panel inline-form" onSubmit={addBatch}><h2>Receive stock</h2><div className="form-grid"><Field label="Batch number" value={batchForm.batchNumber} onChange={(value) => setBatchForm({ ...batchForm, batchNumber: value })} required /><Field label="Expiry date" type="date" value={batchForm.expiryDate} onChange={(value) => setBatchForm({ ...batchForm, expiryDate: value })} required /><Field label="Received date" type="date" value={batchForm.receivedDate} onChange={(value) => setBatchForm({ ...batchForm, receivedDate: value })} /><Field label="Quantity" type="number" min="1" value={batchForm.quantityReceived} onChange={(value) => setBatchForm({ ...batchForm, quantityReceived: value })} required /></div><button className="button button-primary">Receive stock</button></form>}<section className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Stock batches</p><h2>Batch register</h2></div><SortSelect value={batchSort} onChange={(value) => { setBatchSort(value); setBatchPage(1); }}><option value="expiryDate">Expiry</option><option value="receivedDate">Received</option><option value="quantityRemaining">Quantity</option></SortSelect></div>{batches.batches.length ? <><table><thead><tr><th>Batch</th><th>Expiry</th><th>Received</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{batches.batches.map((batch) => <tr key={batch._id}><td><strong>{batch.batchNumber}</strong></td><td>{formatDate(batch.expiryDate)}</td><td>{formatDate(batch.receivedDate)}</td><td>{batch.quantityRemaining}</td><td><Status batch={batch} /></td></tr>)}</tbody></table><div className="table-pagination"><Pagination pagination={batches.pagination} onChange={setBatchPage} /></div></> : <Empty>No batches recorded yet.</Empty>}</section></>;
}

function DispensePage() {
  const [params] = useSearchParams(); const [medicines, setMedicines] = useState([]); const [medicineId, setMedicineId] = useState(params.get('medicineId') || ''); const [stock, setStock] = useState(null); const [quantity, setQuantity] = useState(''); const [reference, setReference] = useState(''); const [result, setResult] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.medicines({ limit: 100, sortBy: 'name' }).then((data) => setMedicines(data.items)).catch((e) => setError(e.message)); }, []);
  useEffect(() => { if (medicineId) api.stock(medicineId).then(setStock).catch((e) => setError(e.message)); }, [medicineId]);
  const submit = async (event) => { event.preventDefault(); setError(''); setResult(null); try { setResult(await api.dispense({ medicineId, quantity: Number(quantity), reference })); setQuantity(''); if (medicineId) setStock(await api.stock(medicineId)); } catch (e) { setError(e.message); } };
  return <><PageHeader eyebrow="Operations" title="Dispense medicine" description="InDate chooses the earliest-expiring valid batches for you." /><div className="two-column"><form className="panel form-card" onSubmit={submit}><h2>Dispensing request</h2><label>Medicine<select required value={medicineId} onChange={(e) => setMedicineId(e.target.value)}><option value="">Select a medicine</option>{medicines.map((medicine) => <option key={medicine._id} value={medicine._id}>{medicine.name}{medicine.strength ? ` · ${medicine.strength}` : ''}</option>)}</select></label>{stock && <div className="available"><span>Sellable now</span><strong>{stock.stock.sellableQuantity} units</strong></div>}<Field label="Quantity" type="number" min="1" value={quantity} onChange={setQuantity} required /><Field label="Reference (optional)" value={reference} onChange={setReference} placeholder="Prescription or sale reference" /><ErrorMessage message={error} /><button className="button button-primary button-wide" disabled={!medicineId}>Confirm dispensing</button></form><section className="panel result-card">{result ? <><p className="eyebrow">Completed</p><h2>Dispensed {result.transaction.dispensedQuantity} units</h2><p className="page-description">Batches used, in FEFO order:</p><div className="allocation-list">{result.allocations.map((allocation) => <div key={allocation.batch}><strong>{allocation.batchNumberSnapshot}</strong><span>{allocation.quantityDispensed} units · expires {formatDate(allocation.expiryDateSnapshot)}</span></div>)}</div><Link className="text-link" to="/history">View dispensing history</Link></> : <><div className="result-icon">FEFO</div><h2>Allocation appears here</h2><p className="page-description">The confirmation will show exactly which batches supplied this request.</p></>}</section></div></>;
}

function AlertsPage() {
  const [days, setDays] = useState(30); const [page, setPage] = useState(1); const [expiredPage, setExpiredPage] = useState(1); const [data, setData] = useState(null); const [expired, setExpired] = useState(null); const [error, setError] = useState('');
  const load = () => Promise.all([api.expiring({ days, page, limit: 10 }), api.expired({ page: expiredPage, limit: 10 })]).then(([soon, old]) => { setData(soon); setExpired(old); }).catch((e) => setError(e.message));
  useEffect(load, [days, page, expiredPage]);
  return <><PageHeader eyebrow="Operations" title="Expiry alerts" description="Prioritise stock that needs attention before it can no longer be sold." action={<label className="sort-control">Window <select value={days} onChange={(e) => { setDays(e.target.value); setPage(1); }}><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label>} /><ErrorMessage message={error} />{!data && !error ? <Loading /> : <div className="alert-stack"><section className="panel"><div className="panel-heading"><div><p className="eyebrow amber-text">Upcoming</p><h2>Expiring within {days} days</h2></div><span className="count-pill amber-pill">{data?.pagination.total || 0}</span></div>{data?.items.length ? <><AlertTable items={data.items} /><Pagination pagination={data.pagination} onChange={setPage} /></> : <Empty>No upcoming expiry alerts.</Empty>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow red-text">Action required</p><h2>Expired stock</h2></div><span className="count-pill red-pill">{expired?.pagination.total || 0}</span></div>{expired?.items.length ? <><AlertTable items={expired.items} expired /><Pagination pagination={expired.pagination} onChange={setExpiredPage} /></> : <Empty>No expired stock with remaining units.</Empty>}</section></div>}</>;
}
function AlertTable({ items, expired = false }) { return <div className="alert-list">{items.map((batch) => <div className="alert-row" key={batch._id}><div><strong>{batch.medicine?.name || 'Medicine'}</strong><span>Batch {batch.batchNumber}</span></div><div><strong>{batch.quantityRemaining} units</strong><span className={expired ? 'red-text' : ''}>{expired ? 'Expired' : `Expires ${formatDate(batch.expiryDate)}`}</span></div></div>)}</div>; }

function HistoryPage() {
  const [tab, setTab] = useState('dispensing'); const [page, setPage] = useState(1); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { const request = tab === 'dispensing' ? api.dispensingHistory({ page, limit: 20 }) : api.stockHistory({ page, limit: 20 }); request.then(setData).catch((e) => setError(e.message)); }, [tab, page]);
  return <><PageHeader eyebrow="Records" title="History" description="A clear trail of stock received and medicine dispensed." /><div className="tabs"><button className={tab === 'dispensing' ? 'active' : ''} onClick={() => { setTab('dispensing'); setPage(1); }}>Dispensing</button><button className={tab === 'stock' ? 'active' : ''} onClick={() => { setTab('stock'); setPage(1); }}>Stock received</button></div><ErrorMessage message={error} />{!data && !error ? <Loading /> : data?.items.length ? <><div className="panel table-panel">{tab === 'dispensing' ? <HistoryTable items={data.items} /> : <StockHistoryTable items={data.items} />}</div><Pagination pagination={data.pagination} onChange={setPage} /></> : <Empty>No history recorded yet.</Empty>}</>;
}
function HistoryTable({ items, compact = false }) { return <div className="history-list">{items.map((item) => <div className="history-row" key={item._id}><div><strong>{item.medicine?.name || 'Medicine'}</strong><span>{formatDateTime(item.createdAt)} · {item.performedBy?.name || 'Pharmacist'}</span></div><div className="history-quantity">-{item.dispensedQuantity} units</div>{!compact && <div className="allocation-summary">{item.allocations?.map((allocation) => <span key={allocation._id}>{allocation.batchNumberSnapshot}: {allocation.quantityDispensed}</span>)}</div>}</div>)}</div>; }
function StockHistoryTable({ items }) { return <div className="history-list">{items.map((item) => <div className="history-row" key={item._id}><div><strong>{item.medicine?.name || 'Medicine'}</strong><span>{item.type} · {formatDateTime(item.createdAt)} · {item.performedBy?.name || 'Pharmacist'}</span></div><div className="history-quantity positive">+{item.quantity} units</div><div className="allocation-summary"><span>{item.batch?.batchNumber}</span></div></div>)}</div>; }

function Field({ label, value, onChange, type = 'text', required = false, ...props }) { return <label>{label}<input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} {...props} /></label>; }
function Status({ batch }) { if (batch.quantityRemaining === 0) return <span className="status neutral">Depleted</span>; if (new Date(batch.expiryDate) < new Date(new Date().setHours(0, 0, 0, 0))) return <span className="status danger">Expired</span>; return <span className="status good">Sellable</span>; }
function formatDate(value) { return value ? new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : '—'; }
function formatDateTime(value) { return value ? new Date(value).toLocaleString(undefined, { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }) : '—'; }

function App() { return <AuthProvider><Routes><Route path="/" element={<LandingPage />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<ProtectedRoute />}><Route path="/dashboard" element={<DashboardPage />} /><Route path="/medicines" element={<MedicinesPage />} /><Route path="/medicines/:medicineId" element={<MedicinePage />} /><Route path="/dispense" element={<DispensePage />} /><Route path="/alerts" element={<AlertsPage />} /><Route path="/history" element={<HistoryPage />} /></Route><Route path="*" element={<NavigateToLogin />} /></Routes></AuthProvider>; }

export default App;
